version: '3.9'

services:
  wireguard:
    container_name: wireguard
    image: lscr.io/linuxserver/wireguard:latest
    #   networks:
    #      t2_proxy:
    #         ipv4_address: 192.168.2.10
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuching
      # - SERVERURL=wireguard.domain.com #optional (Wireguard VPN server address)
      - SERVERPORT=51820 #optional
      - PEERS=Profile1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0/24 #optional (Subnet used in VPN tunnel)
      - ALLOWEDIPS=0.0.0.0/0 #optional
      # - PERSISTENTKEEPALIVE_PEERS= #optional
      # - LOG_CONFS=true #optional
    volumes:
      - /opt/wireguard-server/config:/config
      - /usr/src:/usr/src # location of kernel headers
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
  
  # cp wg0.conf /opt/wireguard-server/config